name: CI_Actions
 
on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
      
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository to VM
        uses: actions/checkout@v3

      - name: run programm
        run: TextAnalyzer.java
